### ISSUE TITLE
Duplicate section headers

### ISSUE THREAD

**Issue by SmogDr** [SmogDr/edar_coursebook#20] opened 2020-08-04 15:45 UTC
I just noticed that when you click on the "Objectives" link on the side navigation bar (for any chapter), the link takes you to the Objectives for Chapter 2.  My guess is that the duplicate section header names (each chapter has an "Objectives" section) is causing this error.  Maybe we insert "Ch. x" into the header names for each instance of chapter objectives so that each is unique?

**Comment by wendtke** [comment] 2020-08-04 21:03
I haven't been able to reproduce this behavior on either a local or deployed book build. Any more details?  Is this happening only in the side panel or within text-based links to the Objective sections?

**Comment by SmogDr** [comment] 2020-08-06 14:43
@wendtke I've seen it happen on the website, and in R after a knit, and/or a full build.  I *think* that differentiating section header titles fixes the issue.

When you are at a good stopping point, will you merge your branch back into Master so that I can mess around in each Chapter?  The changes I intend to make will likely create a bunch of conflicts for you that can be avoided if you merge, wait, and make a new pull afterwards...

**Comment by wendtke** [comment] 2020-08-06 15:31
You can make those changes now. I haven’t made a new branch or PR yet. I was planning and researching for data viz and git yesterday. Let me know when it’s safe to jump back in.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SmogDr** [comment] 2020-08-06 15:39
@wendtke Ha! Thanks.  I suppose I should have checked there first!  Stay tuned.

**Comment by wendtke** [comment] 2020-08-06 22:13
@SmogDr - I'm branching now. Hope it's okay!

**Comment by wendtke** [comment] 2020-08-06 22:14
And it looks like you resolved this issue? I'll close it, but feel free to open it, if it's not done.

**Comment by wendtke** [comment] 2020-08-10 23:31
@SmogDr - this is happening again with the "Class Exercises" and "Homework" sections. A workaround is to put the chapter number in front of each. Tomorrow, we can discuss when might a good time to make that change and in which PR.

**Comment by wendtke** [comment] 2020-08-17 18:33
I rebased my PR with these changes. It should be fine when we merge.

**Closed as completed by wendtke** 2020-08-17 18:33 UTC
